Add consent tracking model
snowplow/documentation pull request #206
Opened 2022-11-29 16:11 UTC by agnessnowplow

Add docs for the upcoming Consent Tracking custom module that will be added to the snowplow-web package.

2022-11-29 17:07 UTC, rlh1994 requested changes
Just a load of random nitpick things, feel free to accept or ignore them depending on whether you think they are easier to read or just make things more complex.

2022-11-29 17:07 UTC, rlh1994 commented on docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/index.md
> +  - `snowplow_web_consent_versions`: Incremental table used to keep track of each consent version and its validity
```suggestion
This custom module consists of a series of dbt models which produce the following aggregated models from the raw consent tracking events:

  - `snowplow_web_consent_log`: Snowplow incremental table showing the audit trail of consent and Consent Management Platform (cmp) events

  - `snowplow_web_consent_users`: Incremental table of user consent tracking stats

  - `snowplow_web_consent_totals`: Summary of the latest consent status, per consent version

  - `snowplow_web_consent_scope_status`: Aggregate of current number of users consented to each consent scope

  - `snowplow_web_cmp_stats`: Used for modeling cmp_visible events and related metrics

  - `snowplow_web_consent_versions`: Incremental table used to keep track of each consent version and its validity
```

2022-11-29 17:07 UTC, rlh1994 commented on docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/index.md
> +```
💡 Can we maybe call out somewhere this is currently only available for bigquery and snowflake?

2022-11-29 17:07 UTC, rlh1994 commented on docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/index.md
> +However, assuming that you already have a working snowplow_web package and you would like to enable consent tracking and modeling at a later stage, you do not need to rebuild the whole model from scr
```suggestion
####  Run the module
If you have previously run the web model without this optional module enabled, you can simply enable the module and run `dbt run --selector snowplow_web` as many times as needed for this module to catch up with your other data. If you only wish to process this from a specific date, be sure to change your `snowplow__start_date`, or refer to the [Custom module](/docs/modeling-your-data/modeling-your-data-with-dbt/dbt-custom-models/index.md) section for a detailed guide on how to achieve this the most efficient way.

If you haven't run the web package before, then you can run it using `dbt run --selector snowplow_web` either through your CLI, within dbt Cloud, or for Enterprise customers you can use the BDP console. In this situation, all models will start in-sync as no events have been processed.

```

2022-11-29 17:07 UTC, rlh1994 commented on docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/index.md
> +Whenever a new consent version is added to be tracked, the model expects an `allow_all` event in order to attribute the events to the full list of latest consent scopes. It is advisable to send a tes
💡 Maybe call this out a little earlier along with the pre-req of loader 4.0.0?

2022-11-29 17:44 UTC, agnessnowplow commented
Just noticed the Enhanced Consent docs are not yet in place so I removed the link (it was pointing at the old Consent plugin) and we can always add it back once it becomes available.

2022-11-30 09:34 UTC, rlh1994 approved these changes
Other than that one typo this looks good to me! Just gotta wait for #204 to go in first.

2022-12-01 09:26 UTC, rlh1994 approved these changes

2022-12-01 09:27 UTC, merged