Next collector release
snowplow/documentation pull request #257
Opened 2023-01-11 16:41 UTC by benjben

2023-01-12 09:09 UTC, stanch requested changes
Could you also bump src/componentVersions.js with the latest version?

2023-01-12 09:09 UTC, stanch commented on docs/pipeline-components-and-applications/stream-collector/configure/index.md
> +| `collector.streams.sink.maxBytes`                                          | Optional. Default: `10000000` (10 MB). Maximum number of bytes that a single record can contain. If a record is bigger,
Add “(since X.Y.Z)”

2023-04-03 10:41 UTC, benjben commented
Sorry the formatting is a pain that hides the changes, that's why I removed it, so that next changes are easy to see.

Important changes are on these lines:
- https://github.com/snowplow/documentation/pull/257/files#diff-2c614c129042458dbebe01e725c2d31aab41a8b1d671ef36f5d68fa3377cdb25R82
- https://github.com/snowplow/documentation/pull/257/files#diff-2c614c129042458dbebe01e725c2d31aab41a8b1d671ef36f5d68fa3377cdb25R84
- https://github.com/snowplow/documentation/pull/257/files#diff-2c614c129042458dbebe01e725c2d31aab41a8b1d671ef36f5d68fa3377cdb25R102
- https://github.com/snowplow/documentation/pull/257/files#diff-2c614c129042458dbebe01e725c2d31aab41a8b1d671ef36f5d68fa3377cdb25R103
- https://github.com/snowplow/documentation/pull/257/files#diff-2c614c129042458dbebe01e725c2d31aab41a8b1d671ef36f5d68fa3377cdb25R124-R126

2023-04-04 07:38 UTC, stanch approved these changes

2023-04-11 11:44 UTC, merged