JS: Mention required Collector config for postPath
snowplow/documentation pull request #305
Opened 2023-02-10 05:25 UTC by jethron

Be more explicit that you need to configure the Collector before you use the `postPath` configuration option in the JS trackers.

Provides links to the respective Collector configuration docs to be super clear. Previously these were mostly only mentioned on https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/snowplow-tracker-protocol/example-requests/

2023-02-10 10:10 UTC, stanch requested changes

2023-02-10 10:10 UTC, stanch commented on docs/collecting-data/collecting-from-own-applications/javascript-trackers/browser-tracker/browser-tracker-v3-reference/tracker-setup/initialization-options/index.md
> +Note: changing `postPath` is non-standard behavior that does not conform to the default collector protocol.
Could you make this a `:::caution`? (https://docusaurus.io/docs/markdown-features/admonitions)

2023-02-10 10:11 UTC, stanch commented on docs/collecting-data/collecting-from-own-applications/javascript-trackers/browser-tracker/browser-tracker-v3-reference/tracker-setup/initialization-options/index.md
> +Note: changing `postPath` is non-standard behavior that does not conform to the default collector protocol.
(Or maybe just a `:::note`)

2023-02-13 22:48 UTC, jethron commented on docs/reusable/untitled-reusable-block-26/_index.md
> +Note: changing `postPath` is non-standard behavior that does not conform to the default collector protocol.
It's a web-centric anti-adblock setting so I'm not sure many other trackers actually support it? Good idea though to keep it DRY.

Also took the moment to name this block, hope that's OK. Sorry for the delay!

2023-02-14 09:35 UTC, stanch approved these changes

2023-02-14 09:36 UTC, merged