Mini 0.17.0
snowplow/documentation pull request #522
Opened 2023-07-05 10:33 UTC by benjben

2023-07-05 10:34 UTC, colmsnowplow approved these changes

2023-07-05 16:55 UTC, stanch requested changes

2023-07-05 16:55 UTC, stanch commented on docs/pipeline-components-and-applications/snowplow-mini/setup-guide-for-aws/index.md
> +<p>In the EC2 Console UI select the <em>Launch Instance</em> button then select the <em>Community AMIs</em> button. In the search bar enter <em>snowplow-mini-{versions.mini}</em> to find the needed A
```suggestion
<p>In the EC2 Console UI select the <em>Launch Instance</em> button then select the <em>Community AMIs</em> button. In the search bar enter <code>snowplow-mini-{versions.mini}</code> to find the needed AMI and then select it.</p>
```

2023-07-05 16:55 UTC, stanch commented on docs/pipeline-components-and-applications/snowplow-mini/setup-guide-for-aws/index.md
> +AMI names explicitly specifies which instance type to use.
```suggestion
AMI names explicitly specify which instance type to use.
```

2023-07-05 16:55 UTC, stanch commented on docs/pipeline-components-and-applications/snowplow-mini/setup-guide-for-aws/index.md
> +<li><em>{versions.mini}-xxlarge</em> needs <em>t2.2xlarge</em></li>
```suggestion
<li><code>{versions.mini}-large</code> needs <code>t2.large</code></li>
<li><code>{versions.mini}-xlarge</code> needs <code>t2.xlarge</code></li>
<li><code>{versions.mini}-xxlarge</code> needs <code>t2.2xlarge</code></li>
```

2023-07-06 08:10 UTC, stanch approved these changes

2023-07-06 08:11 UTC, merged