Update for Snowbridge SLULA change
snowplow/documentation pull request #874
Opened 2024-05-03 15:04 UTC by colmsnowplow

2024-05-09 17:37 UTC, stanch requested changes

2024-05-09 17:37 UTC, stanch commented on docs/contributing/community-license-faq/index.md
> +For example, this does not allow the hosting of any Community Licence version of Snowplow’s Snowbridge product, or other software licensed under the Snowplow Community License, as part of an online s
```suggestion
For example, this does not allow the hosting of any Community License version of Snowplow’s Snowbridge product, or other software licensed under the Snowplow Community License, as part of an online service or distribution of on-premises offerings, that compete with Snowplow products or services.
```

2024-05-09 17:38 UTC, stanch commented
Could you add “Snowbridge (2.4.0+)” to this page? https://docs.snowplow.io/docs/contributing/copyright-license/

2024-05-09 17:45 UTC, colmsnowplow commented
Done. We should wait to merge until release ofc

2024-05-09 17:45 UTC, stanch commented on docs/contributing/copyright-license/index.md
> +* [Snowbridge](/docs/destinations/forwarding-events/snowbridge/) _(2.4.0+)_
```suggestion
* [Snowbridge](/docs/destinations/forwarding-events/snowbridge/index.md) _(2.4.0+)_
```

2024-05-09 17:45 UTC, stanch approved these changes

2024-05-28 13:54 UTC, pondzix commented
Closing in favour of https://github.com/snowplow/documentation/pull/904

2024-05-28 13:54 UTC, closed without merging