Add section calling out realtime streams
snowplow/documentation pull request #982
Opened 2024-08-16 15:11 UTC by jbeemster

2024-08-16 17:36 UTC, stanch commented on docs/getting-started-on-community-edition/quick-start/index.md
> +For an out-of-the-box solution to accessing this data in real-time streams, you can [check out our Snowbridge project](/docs/destinations/forwarding-events/snowbridge/). Alternatively, if you want to
```suggestion
For an out-of-the-box solution to accessing this data in real-time streams, you can [check out our Snowbridge project](/docs/destinations/forwarding-events/snowbridge/index.md). Alternatively, if you want to develop a custom consumer, you can [leverage our Analytics SDKs](/docs/destinations/analytics-sdk/index.md) to parse the event formats more easily.
```

2024-08-16 17:37 UTC, stanch approved these changes

2024-08-16 20:45 UTC, alexanderdean commented on docs/getting-started-on-community-edition/quick-start/index.md
> +## Real-Time Streaming Storage Options
Should be "Real-time streaming storage options" (note the lower case letters) for consistency with other titles...

2024-08-16 20:45 UTC, alexanderdean commented
Made one suggestion, otherwise LGTM!

2024-08-19 09:07 UTC, stanch requested changes

2024-08-19 09:07 UTC, stanch commented on docs/getting-started-on-community-edition/quick-start/index.md
> +## Warehouse storage options
```suggestion
## Storage options
```

2024-08-19 09:07 UTC, stanch commented on docs/getting-started-on-community-edition/quick-start/index.md
> +## Real-time streaming storage options
```suggestion
## Real-time streaming options
```

2024-08-20 09:51 UTC, merged